require: rubocop-rspec

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.4
  Include:
    - '**/Capfile'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'config/initializers/secret_token.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/BlockLength:
  Exclude:
    - '**/Guardfile'
    - '**/*.rake'
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Rails/HttpPositionalArguments:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/InverseOf:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SubjectStub:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/v1/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Enable cops that are disabled by default, but are useful nonetheless
# See https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml

Rails:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true
