files:
  include: 'app/**/*.s+(a|c)ss'

rules:
  indentation:
    - 2
    -
      size: 2

  property-sort-order:
    - 2
    -
      # http://rhodesmill.org/brandon/2011/concentric-css/
      order: 'concentric'

  force-element-nesting:
    - 2

  force-pseudo-nesting:
    - 2

  single-line-per-selector:
    - 2

  no-qualifying-elements:
    - 2

  leading-zero:
    - 2
