language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install 9.11.1
  - node -v
  - npm i -g yarn
  - yarn
jobs:
  include:
  - stage: test
    name: spec
    script: "./bin/ci.sh spec"
  - name: lint
    script: "./bin/ci.sh lint"
env:
  - secure: Gu6fZmHYibhSEq9+2KSLFTDAzAJCYxOE38olJ9nYkSMdA7/HxelT0zLyn16pjTOBLhXEQNVKgQ21j0yXVv9J/jFMhyUcGqZSsln4IKKEaW3MTvYEZMj85PX45bMVHrwFJICcvSX+Hi1loGDy26NtqmovZ23/bNLSYqFd+LOktqMr04jpssR19i3gwGdKBD7bJQdpJaYIfjDJP5TrBvDjh3Npv2CbTCK4fVubYUtG7h6AOWY6hsoxAN1SasA6C232Rn+8fXuPxObywtyfkEtvtXkmWkSb/u0FdRU5XMUQ7sjOB7jXPfD8EMjQRYQEr8FCJ6+y1Nz08oGPjZS0+ungRYOV3tTEQVe/INK3Wkugpg+oJQVppxgX0r7KDprQNRE9WSOnQp3WyL/pQwvM8RAc1bBy7u2McSYpyk3pk62ip9nGkDrzsmLYjdru4oq8N6LyxOfzFLQ7C6E+8puHP16pR2lB4zOJ91FxPzO4CM9+l+McTLpJknHTAzjGm42HgEepjBm7zS0iYbSnWDXhuzoQfqavyIAFAbRjs3kCxHEjUePVbczWaszMMmUsg3FCQS4JSA+PKVMfki0BinpFZW2nmf4ODDoL//nrMQKBgxsYBpAR1+MRJMhvzwlEJvwKWhIxBZcGw8HYAeESx1xeIVmAjnIqm9tjV+LEBVNw+C2neg4=
  - secure: viDlKNs6db/UdQYL7nhW38DUoxlHRkxl5rFob9gM6wWVvbt8p+ngDiQpOLpnDnrF+DB7dol5fvjhPHhXVRlbGkY4c83QQlaHvNxWHnMzjl3XSwG41nx6Es3dBR3N22jE+PSepDimekD+9Q8dY6CrsT8ueo5R+tD8q/cpYbQfW9zZCLXRn/U1hBi4yelE/1s/1FyROI+qgmSycNR9Hfv2JA+x+BuY6uPitWosSmjEeygXPLS8kplFFsZNIIXretfPUFF/TWltMqsahcuF3TgV2SnpZ6Tr3Q5AtY842+rT/MoEPtCfi49pBuWhxaH7CkQnDozegQoYtHLKiKdjsE3TDYmo7aZ5zAXuG7MJmYkTNCYpLhluyUyVcF8TDLooQW7bCKcmRgIoW6l7pvzIuo3paT8Z1SigJlFhPFXTPrlRfnCfdyCpRJK0P/Mw7NvuroKzWSn4qaifvrFHItv9+iSKWqdcXjG/O/qr9w+XDLkcVp2TqsHhkAz7dPFdg2r1rpG6OpOd23Q2c8/cB6GLIHpuRZVJKzVsv3On5itGNCxnA4Rt8NJsit6VdGyDpZemXt+9fOO3hIr6hE9Uowvba9GQuwPTxhKZ1AyRbmMB66khF3QMcjhr6//tFurPOJ06RMVKdnMy7HT98F6RnA+bKtMMhL+QIu6rdp3k/eRDTaADvto=
  - secure: gr8pI5Rsb9OxGJTYMWhgfN/PCti9pjIiy9BBNjm6rs5lnyzJdtA0KbnezLwjYtN8snJ08DWHQpnGfv7XEDDOv07S7X1qUYmSDbXWeVDO45zGAev96jDTchpw2MXpcB/fXJtrNIPwrqorAoIgQ7Qu7SOvwTL0Wgzcml4/v+e+Vre9qyYOSAt+ZGoqCtPrQhJh8CnXxSGKoTyeqceyFEf7o5KTmn9pYQ461Xy68JyHYx/WQufidS135j4LhNUvrEMC/fhi8AhOc8sw9Nh2KqIQpehmO6nSEMCQ3keevbYWgZUyxCvaL/jKy6T9UQipzBDThTdvYNzixkxY4zhxtNqWJZA9jAyJXBhhqfU3QtUOtzGAMsLC3v7z2xACRGC3B8XD4VtgxCCWNFTK6APkFDVmMJL1KF6Cnqk6+MDUMl48ljb/J6jOUroOlYKNCeWmdazvjJFPGwWFAvozVU84CAGlc9XftNrPGPZtiAo92lVP2JHhLMRYC16kURclufYhjHK4dDWEhjJdgf3TMsXt2J9+GW8V7/DJo3xKqz4HcTRz6QCjRtKkQicwnqiqW5LtAdAzeLdw5ZaSbcxP+9xhT1FZA3PZK631UoJcrhYVzVa2mBlH6vAInJfWlDUrANfuH0kVCellw104m4VocefKKoqXFv8MXESTWDOpWvX21TKyP9s=
branches:
  only:
    - master
    - staging
