language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install 9.11.1
  - node -v
  - npm i -g yarn
  - yarn

env:
  - TYPE=spec
  - TYPE=lint

script:
  - './bin/ci.sh $TYPE'

branches:
  only:
    - master
    - staging
