version: '3'

# RAILS_MASTER_KEY must be provided in .env file or ENV
services:
  db:
    env_file: .env # must include POSTGRES_PASSWORD
    image: postgres:9.6.11
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    env_file: .env # must include REDIS_PASSWORD
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/var/lib/redis/data
  sidekiq:
    env_file: .env
    build: .
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    environment:
      - "RAILS_ENV=${RAILS_ENV}"
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - "RAILS_MASTER_KEY=${RAILS_MASTER_KEY}"
  web:
    env_file: .env
    build: .
    ports:
      - "${METAL_WEB_PORT}:5000"
    depends_on:
      - db
      - redis
    environment:
      - "RAILS_ENV=${RAILS_ENV}"
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - "RAILS_MASTER_KEY=${RAILS_MASTER_KEY}"
    volumes:
      - ./log:/app/log

volumes:
  postgres_data:
  redis_data:
