version: '3'

services:
  db:
    env_file: .env
    image: postgres:9.6.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    env_file: .env
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/var/lib/redis/data
  sidekiq:
    env_file: .env
    build: .
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
  web:
    env_file: .env
    build: .
    ports:
      - "${LISTEN_ON_PORT}:5000"
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    volumes:
      - ./log:/app/log

volumes:
  postgres_data:
  redis_data:
