version: '3'

services:
  db:
    image: postgres:11.1
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=test
    depends_on:
      - db
    environment:
      - RAILS_ENV=test
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - RAILS_MASTER_KEY

  app-production:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=production
        - RAILS_MASTER_KEY
