version: '3'

services:
  db:
    image: postgres:11.2
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=test
    depends_on:
      - db

  app-production:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=production
        - RAILS_MASTER_KEY
