steps:
  - label: ":docker: Build test image"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":rspec: Rspec"
    command: "bin/ci.sh"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          env:
            - TYPE=spec
          config: docker-compose.buildkite.yml

  - label: ":rubocop: :html: :eslint: :scsslint: Lint"
    command: "bin/ci.sh"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          env:
            - TYPE=lint
          config: docker-compose.buildkite.yml

  - wait

  - label: ":docker: Build+Push :autoimage_test image"
    branches: "automated-staging-production-docker-images"
    plugins:
      - docker-login#v2.0.1:
          server: docker.csvalpha.nl
          username: csvalpha
          password-env: DOCKER_PASSWORD
      - docker-compose#v2.6.0:
          push: app-production:docker.csvalpha.nl/sofia:autoimage_test
          config: docker-compose.buildkite.yml
          args:
            - RAILS_ENV=production
            - "RAILS_MASTER_KEY=${RAILS_MASTER_KEY}"

  # - label: ":docker: Build & push :staging image"
  #   branches: "staging"
  #   plugins:
  #     - docker-login#v2.0.1:
  #         server: docker.csvalpha.nl
  #         username: csvalpha
  #         password-env: DOCKER_PASSWORD
  #     - docker-compose#v2.6.0:
  #         build: app
  #         push: app:docker.csvalpha.nl/sofia:staging

  # - label: ":docker: Build & push :latest image"
  #   branches: "master"
  #   plugins:
  #     - docker-login#v2.0.1:
  #         server: docker.csvalpha.nl
  #         username: csvalpha
  #         password-env: DOCKER_PASSWORD
  #     - docker-compose#v2.6.0:
  #         build: app
  #         push: app:docker.csvalpha.nl/sofia:latest

  - block: ":shipit: Ready to ship ${BUILDKITE_BRANCH} image?"
    branches: "master staging automated-staging-production-docker-images"
    prompt: "Are you sure you want to deploy ${BUILDKITE_BRANCH} image?"
