steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":rspec: Rspec"
    command: "bin/ci.sh"
    env: "TYPE=spec"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml
      - csvalpha/github-checks#8fb81c0294ce76e2e27163c966c766781f98c731:
          output_title: Rspec

  - label: ":rubocop: :html: :eslint: :scsslint: Lint"
    command: "bin/ci.sh"
    env: "TYPE=lint"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml
      - csvalpha/github-checks#8fb81c0294ce76e2e27163c966c766781f98c731:
          output_title: Lint