steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":rspec: Rspec"
    command: "bin/ci.sh"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          env:
            - TYPE=spec
          config: docker-compose.buildkite.yml

  - label: ":rubocop: :html: :eslint: :scsslint: Lint"
    command: "bin/ci.sh"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          env:
            - TYPE=lint
          config: docker-compose.buildkite.yml