steps:
  - label: ":docker: Build test image"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":rspec: Rspec"
    command: "bin/wait_for -t 30 db:5432 -- bin/ci.sh spec"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: ":rubocop: :html: :eslint: :scsslint: Lint"
    command: "bin/ci.sh lint"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":docker: Build+Push `:staging` image"
    branches: "staging"
    plugins:
      - docker-login#v2.0.1:
          server: docker.csvalpha.nl
          username: buildkite
          password-env: DOCKER_PASSWORD
      - docker-compose#v2.6.0:
          push: app-production:docker.csvalpha.nl/sofia:staging
          config: docker-compose.buildkite.yml

  - label: ":docker: Build+Push `:production` image"
    branches: "master"
    plugins:
      - docker-login#v2.0.1:
          server: docker.csvalpha.nl
          username: buildkite
          password-env: DOCKER_PASSWORD
      - docker-compose#v2.6.0:
          push: app-production:docker.csvalpha.nl/sofia:latest
          config: docker-compose.buildkite.yml

  # Deploy step TBD
  # - block: ":shipit: Ready to ship ${BUILDKITE_BRANCH} image?"
  #   branches: "master staging automated-staging-production-docker-images"
  #   prompt: "Are you sure you want to deploy ${BUILDKITE_BRANCH} image?"
