steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":rspec: Rspec"
    command: "bin/ci.sh"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml
          env:
            - TYPE=spec
      - csvalpha/github-checks#3418fd07d0f5:

  - label: ":rubocop: :html: :eslint: :scsslint: Lint"
    command: "bin/ci.sh"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml
          env: 
            - TYPE=lint
      - csvalpha/github-checks#3418fd07d0f5: