default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: <%= ENV['POSTGRES_HOST'] %> # defined in docker-compose
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: alpha-tomato_development

test:
  <<: *default
  database: alpha-tomato_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_USER'] %>
