defaults: &defaults
  sentry_dsn: <%= ENV["SENTRY_DSN"] || "''" %>
  banana_client_id: <%= ENV["BANANA_CLIENT_ID"] || "''" %>
  banana_client_secret: <%= ENV["BANANA_CLIENT_SECRET"] || "''" %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "''" %>
  slack_webhook: 'https://hooks.slack.com/services/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'

development:
  <<: *defaults

test:
  <<: *defaults
  secret_key_base: e3d3304b39dc13f2fbd50ce6bef4e3635cafd7bc81eb5421976665539b8279fad2c67b9336e2853d8b5104777b8fc9199bd20bf383a0beab291c8cd1cf6c2cb8
  banana_client_id: a46ccf8d4a6cb4119958924dc1865237e3596a2b7c1461a234f4d58e4ed554a8
  banana_client_secret: 3a4afdb72f83a2d219de1149589cf169f8744e1dcfa9be699aa54a61065d9b98

production:
  <<: *defaults
