defaults: &defaults
  sentry_dsn: <%= ENV["SENTRY_DSN"] || "''" %>
  banana_client_id: <%= ENV["BANANA_CLIENT_ID"] || "''" %>
  banana_client_secret: <%= ENV["BANANA_CLIENT_SECRET"] || "''" %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "''" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
