:queues:
  - default
  - mailers

schedule:
  SlackMessageJob:
    cron: '0 0 10 * * 4'  # At 10:00:00 on Thursday => https://crontab.guru/#0_10_*_*_4
    args: ['Poke the bear, poke slack via SlackMessageJob']
