:concurrency: 10
:queues:
  - default
  - mailers

schedule:
  CreditInsufficientNotificationJob:
    cron: '0 0 10 * * 4'  # At 10:00:00 on Thursday => https://crontab.guru/#0_10_*_*_4
  HealthCheckJob:
    cron : '*/30 * * * *' # Every 30 minutes => https://crontab.guru/#*/30_*_*_*_*
    args: ['sidekiq']
